[tool.poetry]
name = "psp"
version = "0.1.0"
description = "Photovoltaic per site modeling"
authors = ["Simon Lemieux <1105380+simlmx@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scikit-learn = "^1.1.3"


[tool.poetry.group.dev.dependencies]
dataset = "^1.5.2"
datasets = "^2.7.1"
jupyter = "^1.0.0"
xarray = {extras = ["complete"], version = "^2022.11.0"}
altair = "^4.2.0"
pyzstd = "^0.15.3"
altair-saver = "^0.5.0"
selenium = "4.2.0"
plotly = "^5.11.0"
astral = "^3.2"
pytest = "^7.2.0"
flake8 = "^6.0.0"
isort = "^5.10.1"
jupyter-contrib-nbextensions = "^0.7.0"
black = {extras = ["jupyter"], version = "^22.10.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
