on:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: poetry install

      - name: Run lint
        run: make lint

      - name: Format
        if: failure() && github.ref != 'refs/heads/master'
        run: make format
      - name: Commit
        if: failure() && github.ref != 'refs/heads/master'
        uses: EndBug/add-and-commit@v9

      # - run: make lint
      - name: Run tests
        run: make test
